### ISSUE TITLE
Thanks and referall to lib for new BLE firmware

### ISSUE THREAD

**Issue by dnandha** [scooterhacking/NinebotCrypto#8]
Hey guys, just wanted to leave props for sharing all of this information!

I have ported the lib to Python and integrated it into a command line utility for authorization with the legacy Nb and the new Mi EC protocol. It all works, tested on my own scooter.

Check it out and feel free to adapt SHCU for newer BLE firmware support: https://github.com/dnandha/miauth

**Comment by robbiet480** [comment]
Excellent job @dnandha, thanks!

**Comment by RiccardoCestaro** [comment]
Are you talking about protocol 55AB for scooters? Does anyone know how it works?

**Comment by dnandha** [comment]
@RiccardoCestaro Yes I am.

The repo contains Python and Java libraries for 55AB. 
Also in-depth description / explanation of protocol is here: [https://github.com/dnandha/miauth/tree/main/doc](https://github.com/dnandha/miauth/tree/main/doc).
